### ISSUE TITLE
Fails to mint

### ISSUE THREAD

**Issue by sideninja** [onflow/scaffold-flow#19]
### Current Behavior

There's an error when minting

### Expected Behavior

/

### Steps To Reproduce

/

### Environment

```markdown
HTTP Request Error: An error occurred when interacting with the Access API.
      error=invalid event type format
      hostname=http://localhost:8888
      path=/v1/events?type=A.null.BlockTalk.TalkSaved&start_height=2&end_height=2
      method=GET
      
      responseBody={
	"code": 400,
	"message": "invalid event type format"
}
      responseStatusText=Bad Request
      statusCode=400
```

**Comment by sideninja** [comment]
Related to FCL not correctly resolving addresses in flow.json if not including 0x prefix. Once I add 0x prefix to addresses in flow.json this issue goes away.
CC @justinbarry

**Comment by devbugging** [comment]
looks like it. was related to cache
